# TODO: add repo for docker and podman

- name: Install core packages for all systems
  become: true
  ansible.builtin.dnf:
    name:
      # Networking
      - nmtui

      # Flatpaks
      - flatpak
      - stow

      # AppImage
      - fuse-libs

      # Virtualization groupinstall
      - "@virtualization"

      # Container
      - podman
      - repoquery

      # Docker - keep for development of some open source projects
      - dnf-plugins-core
      #- docker-ce 
      #- docker-ce-cli 
      #- containerd.io 
      #- docker-buildx-plugin 
      #- docker-compose-plugin

- name: Start libvirtd
  become: true
  systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Add user to libvirt group
  become: true
  user:
    name: soonann
    append: true
    groups: libvirt

#- name: Start docker
#  become: true
#  systemd:
#    name: docker
#    state: started
#    enabled: true

#- name: Add user to docker group
#  become: true
#  user:
#    name: soonann
#    append: true
#    groups: docker

