- name: Install core packages for all systems
  become: true
  ansible.builtin.dnf:
    name:
      # Networking
      - nmtui

      # Flatpaks
      - flatpak
      - stow

      # AppImage
      - fuse-libs

      # Virtualization groupinstall
      - "@virtualization"

      # Container
      - podman
      - repoquery

- name: Start libvirtd
  become: true
  systemd:
    name: libvirtd
    state: started
    enabled: true

- name: Add user to libvirt group
  become: true
  user:
    name: soonann
    append: true
    groups: libvirt

