---
- name: Installing dependencies and make symlinks
  hosts: localhost
  connection: local

  # set where you've cloned the dotfiles to
  vars_prompt:
    - name: dotfiles_path
      prompt: Enter the full path of the dotfiles
      default: $HOME/dotfiles
      private: no

  tasks:
  - name: Install nvim
    shell: sudo dnf install neovim -y

  - name: Install tmux
    shell: sudo dnf install tmux -y

  - name: Install alacritty
    shell: sudo dnf install alacritty -y

  - name: Install docker
    shell: sudo dnf install docker docker-compose -y

  - name: Install file navigation tools
    shell: sudo dnf install fzf ripgrep fd-find ranger -y

  - name: Install common cli utilities
    shell: sudo dnf install htop curl wget -y

  # https://docs.rancherdesktop.io/getting-started/installation/
  - name: Install rancher dependencies
    shell: sudo dnf install pass gnupg2 -y

  # link tmux dotfiles
  - name: Create symlink for tmux
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/tmux/.tmux.conf"
      dest: $HOME/.tmux.conf
      state: link

  # link tmux-sessionizer
  - name: Create symlink for tmux-sessionizer
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/tmux/tmux-sessionizer"
      dest: $HOME/.local/bin/tmux-sessionizer
      state: link

  # link nvim dotfiles
  - name: Create symlink for nvim
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/nvim"
      dest: $HOME/.config/nvim
      state: link

  # link alacritty dotfiles
  - name: Create symlink for alacritty
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/alacritty"
      dest: $HOME/.config/alacritty
      state: link
