---
- name: Installing dependencies and make symlinks
  hosts: localhost
  connection: local

  # check if homebrew is installed
  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing, install from http://brew.sh
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

    - name: Create $HOME/.local/bin if it doesn't exist
      shell: mkdir -p $HOME/.local/bin

  # set where you've cloned the dotfiles to
  vars_prompt:
    - name: dotfiles_path
      prompt: Enter the full path of the dotfiles
      default: $HOME/dotfiles
      private: no

  tasks:

  # install dependnecies using homebrew
  - name: Install nvim
    shell: brew install neovim

  - name: Install tmux
    shell: brew install tmux

  - name: Install alacritty
    shell: brew install alacritty

  - name: Install docker
    shell: brew install docker docker-compose

  - name: Install common cli tools
    shell: brew install fzf rg fd tmux htop curl wget 


  # link tmux dotfiles
  - name: Create symlink for tmux
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/tmux/.tmux.conf"
      dest: $HOME/.tmux.conf
      state: link

  # link tmux-sessionizer
  - name: Create symlink for tmux-sessionizer
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/tmux/tmux-sessionizer"
      dest: $HOME/.local/bin/tmux-sessionizer
      state: link

  # link nvim dotfiles
  - name: Create symlink for nvim
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/nvim"
      dest: $HOME/.config/nvim
      state: link

  # link alacritty dotfiles
  - name: Create symlink for alacritty
    ansible.builtin.file:
      src: "{{ dotfiles_path }}/alacritty"
      dest: $HOME/.config/alacritty
      state: link
