- name: Install dnf related packages
  become: true
  ansible.builtin.dnf:
    state: latest
    name:
      - git-lfs
      # - alacritty fedora
      - tmux

      - fzf
      - ripgrep
      - fd-find
      
      - cargo
      - go
      # - node
      - nodejs

      - atop
      - htop
      - btop
      - nvtop
      
- name: Install Tmux Plugin Manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Link dotfiles
  ansible.builtin.shell: stow * -t $HOME
  args:
    chdir: "{{ role_path }}/files"

- name: Setup node prefix directory user level directory
  ansible.builtin.shell: |
    npm config set prefix ~/.npm
