- name: Add flathub remote
  community.general.flatpak_remote:
    name: "flathub"
    method: user
    flatpakrepo_url: "https://dl.flathub.org/repo/flathub.flatpakrepo"

- name: Install Flatpaks
  community.general.flatpak:
    method: user
    remote: "flathub"
    name:
      - com.brave.Browser
      - md.obsidian.Obsidian
      - org.telegram.desktop
      - com.discordapp.Discord

      - com.spotify.Client
      - org.videolan.VLC
      - org.libreoffice.LibreOffice
      - org.onlyoffice.desktopeditors
      - com.bambulab.BambuStudio
