# functionality
gsettings set org.gnome.mutter dynamic-workspaces false 
gsettings set org.gnome.desktop.interface enable-hot-corners false
gsettings set org.gnome.shell.app-switcher current-workspace-only false
gsettings set org.gnome.desktop.wm.preferences num-workspaces 10 
gsettings set org.gnome.shell.keybindings switch-to-application-1 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-2 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-3 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-4 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-5 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-6 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-7 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-8 [] 
gsettings set org.gnome.shell.keybindings switch-to-application-9 [] 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 "['<Alt>1']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 "['<Alt>2']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 "['<Alt>3']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 "['<Alt>4']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-5 "['<Alt>5']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-6 "['<Alt>6']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-7 "['<Alt>7']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-8 "['<Alt>8']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-9 "['<Alt>9']" 
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-10 "['<Alt>0']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 "['<Alt><Shift>1']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 "['<Alt><Shift>2']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 "['<Alt><Shift>3']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 "['<Alt><Shift>4']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-5 "['<Alt><Shift>5']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-6 "['<Alt><Shift>6']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-7 "['<Alt><Shift>7']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-8 "['<Alt><Shift>8']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-9 "['<Alt><Shift>9']" 
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-10 "['<Alt><Shift>0']"
gsettings set org.gnome.settings-daemon.plugins.media-keys search "['<Alt>D']"
gsettings set org.gnome.shell.keybindings show-screenshot-ui "['<Alt><Shift>S']"
gsettings set org.gnome.desktop.peripherals.keyboard delay 280
gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 40

# aesthetics
gsettings set org.yorba.shotwell.preferences.ui use-dark-theme true
