#!/usr/bin/env bash

res=$(xinput list-props 'keyboard:Razer Razer Blade Keyboard' | grep 'Device Enabled' | sed 's/Device Enabled (204):.*\(1\|0\).*/\1/')
if [[ "$res" =~ "1" ]]; then
  xinput set-prop 'keyboard:Razer Razer Blade Keyboard' 'Device Enabled' 0
else
  xinput set-prop 'keyboard:Razer Razer Blade Keyboard' 'Device Enabled' 1
fi
