#!/usr/bin/env bash

res=$(xinput list-props 17 | grep 'Device Enabled' | sed 's/Device Enabled (202):.*\(1\|0\).*/\1/')
if [[ "$res" =~ "1" ]]; then
  xinput set-prop 17 'Device Enabled' 0
else
  xinput set-prop 17 'Device Enabled' 1
fi
