#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
	selected_dir=$1
else
	selected_dir=$(find ~ ~/development ~/dotfiles -mindepth 1 -maxdepth 4 -type d | fzf)
fi

if [[ -z $selected_dir ]]; then
	exit 0
fi

# hash prefixes
session_name="$(basename "$selected_dir" | tr . _)-$(sha1sum <<< "$selected_dir" | cut -c 1-5)"

# original 
# session_name=$(basename "$selected_dir" | tr . _)

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
	tmux new-session -s $session_name -c $selected_dir
	exit 0
fi

if ! tmux has-session -t=$session_name 2> /dev/null; then
	tmux new-session -ds $session_name -c $selected_dir
fi

tmux switch-client -t $session_name
tmux setenv -t $session_name TMUX_SESS_ROOT $selected_dir
