#!/bin/sh

PATH=/sbin:/usr/sbin:/bin:/usr/bin

case "$1" in
    pre)
            # run before suspend/hibernate
    ;;
    post)
            # run on waking up...
            xset r rate 280 40
    ;;
esac
exit 0
