
- name: Install system dependencies
  become: true
  ansible.builtin.dnf:
    state: latest
    name:
      - polybar
      - rofi
      - lxappearance

      - xinput
      - xset

      - arandr
      - xrandr 

      - blueman

      - pamixer
      - light

      # Compositor
      - picom

# - name: Install greenclip
