
- name: Install system dependencies
  become: true
  ansible.builtin.dnf:
    state: latest
    name:

      # I/O
      - xinput
      - xset

      # Display
      - arandr
      - xrandr 

      # Light, sound, bluetooth
      - pamixer
      - light
      - blueman

      # Drag and drop
      - dragon

      # Compositor
      - picom

      # Aesthetics
      - polybar
      - rofi
      - lxappearance


# - name: Install greenclip
