---
- name: installing dependencies and make symlinks
  hosts: localhost
  connection: local

  # set where you've cloned the dotfiles to
  vars_prompt:
    - name: dotfiles_path
      prompt: Enter the full path of the dotfiles
      default: $HOME/dotfiles
      private: no
  
  tasks:

  # install tailscale
  - name: check if tailscale bin exists
    stat:
      path: /usr/bin/tailscale
    register: tailscale_bin

  - name: install tailscale if the bin does not exist
    become: true
    shell: |
      curl -fsSL https://tailscale.com/install.sh | sh
    when: not tailscale_bin.stat.exists

  # install vlc - prefer a more stable version 
  - name: install vlc
    become: true
    ansible.builtin.apt:
      pkg:
      - vlc

  # install flatpak
  - name: install flatpak/flathub
    become: true
    ansible.builtin.apt:
      pkg:
      - flatpak
      - gnome-software-plugin-flatpak

  - name: add flatpak remote
    shell: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

  # install flatpak packages
  - name: install flatpaks from flathub
    shell: "{{ dotfiles_path }}/flatpak/flatpak-apps.sh"

