[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family="Hack Nerd Font"


[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[terminal.shell]
program = "/bin/bash"

[window]
dynamic_title = true
opacity = 0.8
startup_mode = "Maximized"

[window.padding]
x = 4
y = 4

[terminal]
